### ISSUE TITLE
Break statement

### ISSUE THREAD

**Issue by norbert-gaulia** [contek-io/io.contek.invoker#14]
I'm not sure is it a bug or intention does [this line ](https://github.com/contek-io/io.contek.invoker/blob/0710b6f75b82a9f488c95b2b53ee89cf54e8a166/commons/src/main/java/io/contek/invoker/commons/websocket/WebSocketComponentManager.java#L35) needs break statement?

**Comment by norbertas-gaulia** [comment]
Disregard, figured its bucket switching logic.

**Comment by beijunyi** [comment]
It is intentional.. However, I agree that it might need a line of comment.

**Comment by Cypher01** [comment]
I think this issue should be closed.
