### ISSUE TITLE
BigDecimal vs Double

### ISSUE THREAD

**Issue by davidjirovec** [contek-io/io.contek.invoker#19]
This library looks promising, but why do you use Double instead of BigDecimal? Any plans on using BigDecimal?

**Comment by beijunyi** [comment]
We actually had an internal debate over this topic. BigDecimal keeps precision when you do calculations. However, this library mostly just parses JSON into objects and hardly has any calculation. Using BigDecimal makes things slower with no gain.

**Comment by davidjirovec** [comment]
Did you do any measurements how much slower it actually is? What is parsing
without doing any calculations good for? I believe using BigDecimal would
not be such performance hit and would be universal to use for any thing.

**Comment by beijunyi** [comment]
The actual performance impact very much depends on what you want to do with the numbers.
The philosophy in this project is to have minimal assumptions meaning it should do no more than parsing JSON into plain old objects.

In our case, we have an internal layer on top of this lib, which is a unified GRpc API. We don't want to convert JSON strings/numbers into BigDecimals and then convert them back to doubles again.
