### ISSUE TITLE
Correct JDK version

### ISSUE THREAD

**Issue by Cypher01** [contek-io/io.contek.invoker#57]
The file .github/workflows/main.yml says, the project uses JDK 15.
The build.gradle file configures the sourceCompatibility and targetCompatibility to JDK 1.8.
Which version should be used to build the project?

I could build the project with JDK 17, but it caused a bunch of warnings.
I could also build the project with JDK 1.8, except for the module bybitlinear-api.

The JDK version should be aligned over all project files.

**Comment by beijunyi** [comment]
targetCompatibility = '1.8'

.github/workflows/main.yml is now deleted
